language: python
sudo: true
python:
    - "3.8"
    - "3.10"

install:
  - "poetry install"

#before_script:
#  - "flake8 setup.py mppsolar tests"

script:
  - "make test"

after_success:
  - "coverage report"
  - "coveralls"

notifications:
  email: false
